#!/bin/bash

# Environment Setup Script
# 
# This script helps set up environment variables for development or production.
# 
# Usage:
#   ./scripts/setup-env.sh [local|production]
#   ./scripts/setup-env.sh local      # Set up .env.local
#   ./scripts/setup-env.sh production # Set up .env.production

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Functions
print_header() {
    echo -e "${BLUE}========================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}========================================${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

read_input() {
    local prompt="$1"
    local default="$2"
    local input
    
    if [ -z "$default" ]; then
        read -p "$(echo -e ${BLUE}$prompt${NC}): " input
    else
        read -p "$(echo -e ${BLUE}$prompt${NC}) [${default}]: " input
        input="${input:-$default}"
    fi
    
    echo "$input"
}

# Main script
main() {
    local env_type="${1:-local}"
    
    if [ "$env_type" != "local" ] && [ "$env_type" != "production" ]; then
        print_error "Invalid environment type: $env_type"
        echo "Usage: ./scripts/setup-env.sh [local|production]"
        exit 1
    fi
    
    local env_file=".env.${env_type}"
    
    print_header "Environment Setup - ${env_type^^}"
    
    # Check if file already exists
    if [ -f "$env_file" ]; then
        print_warning "$env_file already exists"
        read -p "Do you want to overwrite it? (y/n): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            print_info "Setup cancelled"
            exit 0
        fi
    fi
    
    # Create backup if file exists
    if [ -f "$env_file" ]; then
        cp "$env_file" "${env_file}.backup"
        print_success "Backup created: ${env_file}.backup"
    fi
    
    # Start collecting variables
    echo ""
    print_info "Please provide the following information:"
    echo ""
    
    # ANTHROPIC_API_KEY
    print_header "Claude API Configuration"
    print_info "Get your API key from: https://console.anthropic.com/account/keys"
    local anthropic_key=$(read_input "Enter ANTHROPIC_API_KEY")
    
    if [ -z "$anthropic_key" ]; then
        print_error "ANTHROPIC_API_KEY is required"
        exit 1
    fi
    
    # SUPABASE Configuration
    echo ""
    print_header "Supabase Configuration"
    print_info "Get these from: https://app.supabase.com/project/[project-id]/settings/api"
    
    local supabase_url=$(read_input "Enter SUPABASE_URL" "https://your-project.supabase.co")
    local supabase_service_key=$(read_input "Enter SUPABASE_SERVICE_KEY")
    local public_supabase_url=$(read_input "Enter PUBLIC_SUPABASE_URL" "$supabase_url")
    local public_supabase_anon_key=$(read_input "Enter PUBLIC_SUPABASE_ANON_KEY")
    
    if [ -z "$supabase_url" ] || [ -z "$supabase_service_key" ] || [ -z "$public_supabase_anon_key" ]; then
        print_error "Supabase configuration is incomplete"
        exit 1
    fi
    
    # VOYAGE_API_KEY (optional)
    echo ""
    print_header "Voyage AI Configuration (Optional)"
    print_info "Get your API key from: https://dash.voyageai.com/api-keys"
    local voyage_key=$(read_input "Enter VOYAGE_API_KEY (leave blank to skip)")
    
    # Create .env file
    echo ""
    print_info "Creating $env_file..."
    
    cat > "$env_file" << EOF
# Generated by setup-env.sh on $(date)
# Environment: ${env_type^^}

# ============================================================================
# ANTHROPIC API - Claude AI Integration
# ============================================================================
ANTHROPIC_API_KEY=${anthropic_key}

# ============================================================================
# SUPABASE - Database and Backend Services
# ============================================================================
SUPABASE_URL=${supabase_url}
SUPABASE_SERVICE_KEY=${supabase_service_key}
PUBLIC_SUPABASE_URL=${public_supabase_url}
PUBLIC_SUPABASE_ANON_KEY=${public_supabase_anon_key}

# ============================================================================
# VOYAGE AI - Vector Embeddings for Semantic Search (Optional)
# ============================================================================
EOF
    
    if [ -n "$voyage_key" ]; then
        echo "VOYAGE_API_KEY=${voyage_key}" >> "$env_file"
    fi
    
    print_success "$env_file created successfully"
    
    # Verify setup
    echo ""
    read -p "Do you want to verify the setup now? (y/n): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo ""
        print_info "Running verification..."
        
        if [ "$env_type" = "local" ]; then
            npm run verify:local-env
        else
            npm run verify:prod-env
        fi
    fi
    
    echo ""
    print_success "Setup complete!"
    echo ""
    print_info "Next steps:"
    echo "  1. Review $env_file to ensure all values are correct"
    echo "  2. Run: npm run verify:${env_type}-env"
    echo "  3. For development: npm run dev"
    echo "  4. For production: Follow DEPLOYMENT.md"
    echo ""
}

# Run main function
main "$@"
