-- ============================================================================
-- Advisor thread: per-message rows + read state
-- Created: 2026-08-03
-- ============================================================================

-- ── 1. One row per advisor turn ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS advisor_messages (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  assistant_type  TEXT NOT NULL CHECK (assistant_type IN ('wingman', 'bestie')),
  role            TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
  kind            TEXT NOT NULL DEFAULT 'chat'
                  CHECK (kind IN ('chat', 'greeting', 'nudge', 'task_ack', 'task_result')),
  content         TEXT NOT NULL,
  payload         JSONB,
  greeting_id     UUID REFERENCES ai_assistant_greetings(id) ON DELETE SET NULL,
  task_id         UUID,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  seq             BIGINT GENERATED BY DEFAULT AS IDENTITY
);

CREATE INDEX IF NOT EXISTS idx_advisor_messages_thread
  ON advisor_messages (user_id, assistant_type, seq);

CREATE INDEX IF NOT EXISTS idx_advisor_messages_unread
  ON advisor_messages (user_id, assistant_type, created_at)
  WHERE role = 'assistant';

CREATE INDEX IF NOT EXISTS idx_advisor_messages_task
  ON advisor_messages (task_id)
  WHERE task_id IS NOT NULL;

-- ── 2. Per-thread read state ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS advisor_read_state (
  user_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  assistant_type  TEXT NOT NULL CHECK (assistant_type IN ('wingman', 'bestie')),
  last_read_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, assistant_type)
);

-- ── 3. RLS ────────────────────────────────────────────────────────────────────
ALTER TABLE advisor_messages   ENABLE ROW LEVEL SECURITY;
ALTER TABLE advisor_read_state ENABLE ROW LEVEL SECURITY;

-- ── 4. Backfill existing threads ─────────────────────────────────────────────
INSERT INTO advisor_messages (user_id, assistant_type, role, kind, content, payload, created_at)
SELECT
  c.user_id,
  c.assistant_type,
  CASE WHEN m.value->>'role' = 'user' THEN 'user' ELSE 'assistant' END,
  'chat',
  m.value->>'content',
  CASE WHEN m.value->>'id' IS NOT NULL
    THEN jsonb_build_object('legacy_latency_id', m.value->>'id')
    ELSE NULL END,
  COALESCE((m.value->>'ts')::timestamptz, c.created_at)
FROM ai_assistant_advisor_chats c
CROSS JOIN LATERAL jsonb_array_elements(c.messages) WITH ORDINALITY AS m(value, ord)
WHERE jsonb_typeof(c.messages) = 'array'
  AND COALESCE(m.value->>'content', '') <> ''
  AND NOT EXISTS (
    SELECT 1 FROM advisor_messages am
    WHERE am.user_id = c.user_id
      AND am.assistant_type = c.assistant_type
  )
ORDER BY c.user_id, c.assistant_type,
         COALESCE((m.value->>'ts')::timestamptz, c.created_at), m.ord;

INSERT INTO advisor_read_state (user_id, assistant_type, last_read_at)
SELECT user_id, assistant_type, MAX(created_at)
FROM advisor_messages
GROUP BY user_id, assistant_type
ON CONFLICT (user_id, assistant_type) DO NOTHING;

COMMENT ON TABLE advisor_messages IS
  'Canonical per-message transcript of the owner-facing AI Wingman/Bestie advisor thread. The app reads this; ai_assistant_advisor_chats is the legacy QA aggregate.';
COMMENT ON COLUMN advisor_messages.seq IS
  'Deterministic intra-thread order. Do not order on created_at alone — legacy rows share timestamps within an exchange.';
COMMENT ON TABLE advisor_read_state IS
  'Per-thread last_read_at driving the advisor unread badge, mirroring verified_vibe_matches.userN_last_read_at.';;
